Repository ucsb-cs156-s22/s22-6pm-happycows, pull requests merged in 2022-06, with the labels that each got.

#62 S22-6pm-4 laszlo (kz) - added showLeaderboard to frontend and backend admin CRUD operations
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-6pm-4

#56 pc - add link to dashboard for production heroku
  README.md
  frontend/src/tests/components/Commons/CommonsForm.test.js
Labels: s22-staff

#54 S22 6pm 3 dj - add leaderboard sorting utilities
  frontend/src/main/utils/leaderboardSortingUtils.js
  frontend/src/tests/utils/leaderboardSortingUtils.test.js
Labels: s22-6pm-3, :+1: Merge Candidate, :hourglass_flowing_sand: Waiting on CI/CD

#55 S22-6pm-4 Katya (KR) - added field degradation rate to update commons and create commons API
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10, s22-6pm-4

#58 s22-6pm-3 Created a Leaderboard Table that displays a list of users and their Attributes
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/stories/components/Leaderboard/LeaderboardTable.stories.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 5, 10, s22-6pm-3

#50 s22-6pm-4 nm - add degradationRate to form and table components
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: 10, s22-6pm-4, :+1: Merge Candidate, :hourglass_flowing_sand: Waiting on CI/CD

#64 s22-6pm-4 lv - Show Leaderboard column in CommonsTable
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10, s22-6pm-4, :+1: Merge Candidate, :hourglass_flowing_sand: Waiting on CI/CD

#69 s22-6pm-4 Adrian update footer link to GitHub repo
  frontend/src/main/components/Nav/Footer.js
Labels: s22-6pm-4

#59 s22-6pm-3 as- Added GetUserCommonsByCommonsId to backend (CherryPicked)
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/UserCommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, s22-6pm-3

#72 s22-6pm-4 Adrian display field starting date as YYYY-MM-DD in CommonsTable for readability
  frontend/src/main/components/Commons/CommonsTable.js
Labels: 5, s22-6pm-4, :hourglass_flowing_sand: Waiting on CI/CD

#73 s22-6pm-4 lv - updated tab display title from React App to Happier Cows
  frontend/public/index.html
Labels: s22-6pm-4

#76 s22-6pm-4 lv - Change site icon to cow
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
Labels: s22-6pm-4

#74 s22-6pm-3 Changed Columns in LeaderboardTable.js + Adopted those Changes to Tests and Storybook + Fixed Bug with Profits
  frontend/src/App.js
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Leaderboard/LeaderboardTable.stories.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: s22-6pm-3

#79 s22-6pm-3 Created Leaderboard page and tests
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: s22-6pm-3

#88 s22-6pm-3 - ml - add user leaderboard button onto play page + test
  .DS_Store
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
Labels: s22-6pm-3

#90 s22-6pm-3 hide and show leaderboard button appropriately
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: s22-6pm-3

#95 m22 - sk - (recreate 4pm PR92) fix initialization of cow number to start at 0 instead of 1
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: M22

#96 m22 - sk - (recreate 4pm PR85) to remove available commons list from homepage
  frontend/src/main/pages/LoginPage.js
  frontend/src/tests/pages/LoginPage.test.js
Labels: M22

#89 s22-6pm-4 Adrian - fixes undefined toast message in admin edit commons
  frontend/src/main/pages/AdminEditCommonsPage.js
Labels: s22-6pm-4, :hourglass_flowing_sand: Waiting on CI/CD

#77 s22-6pm-4 Adrian - added newlines to Toast successful commons creation message
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: s22-6pm-4

#83 s22-6pm-3 - dj - add end date to commons backend 3
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-6pm-3

#100 m22 - sk - (recreate 5pm PR85) incorporate 5pm's 404 page not found into 6pm codebase
  frontend/src/App.js
  frontend/src/main/pages/NotFoundPage.js
  frontend/src/stories/pages/NotFoundPage.stories.js
  frontend/src/tests/pages/NotFoundPage.test.js
Labels: :hourglass_flowing_sand: Waiting on CI/CD, M22

#111 pc - add placeholder for Admin / Manage Jobs
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: M22
