Repository ucsb-cs156-s22/s22-6pm-happycows, pull requests merged in 2022-05, with the labels that each got.

#14 6pm-4, sk - updated heroku production deployment url in readme file
  README.md
Labels: s22-6pm-4

#36 6pm-4 Add showLeaderboard boolean to commons database entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
Labels: 5, s22-6pm-4

#30 6pm-3, dj-Add 6pm-3 heroku QA and QA dashboard links to README
  README.md
Labels: 5, s22-6pm-3

#15 6pm-4 qa heroku deployment
  README.md
Labels: s22-6pm-4

#46 s22-6pm-3 yl - Added storybook qa and docs links to README.md
  README.md
Labels: s22-6pm-3

#43 s22-6pm-4 Nav bar storybook improvements
  frontend/src/stories/components/Nav/AppNavbar.stories.js
Labels: s22-6pm-4, :+1: Merge Candidate

#32 Staff PC: Pull in code to run async jobs, and address backend testing tech debt
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/HappierCowsApplication.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/jobs/JobsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContext.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContextConsumer.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobService.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CSRFControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserTests.java
Labels: s22-staff, :+1: Merge Candidate

#40 s22-6pm-3 - zm - add fields to commonsFixtures.js and fixtures to userCommonsFixtures.js
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
Labels: s22-6pm-3

#33 s22-6pm-4 Adrian - added field degradationRate to commons entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
Labels: s22-6pm-4

#48 S22-6pm-4 laszlo (kz) - added showLeaderboard to frontend and backend admin CRUD operations
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-6pm-4
